branches:
  only:
  - master
platform:
- x86
- x64
environment:
  NODEJS_VERSION: "8"
  PREBUILD_UPLOAD:
    secure: C1k8S2BGncdH8/USTMjAgYx5MwOhPb/1fPaZbDiUKmcrMthKc19/RSm6fT0iGZcD
install:
- ps: Install-Product node $env:NODEJS_VERSION $env:Platform
- node --version
- npm --version
- npm install
build: off
test_script:
- npm run test
deploy_script: npm run prebuild && npm run prebuild:upload -u %PREBUILD_UPLOAD%
